* What is it.
~emms-player-spotify~ is an EMMS player implementation that supports playback of
Spotify tracks. It does so by controlling a running Spotify app via the D-Bus
MPRIS interface.

Features:
- player's state is synchronised between EMMS and Spotify
  - manual seeking in spotify is recognized by EMMS
  - play/pause works in both directions
- supports muting ads
- ~emms-player-spotify-following~ minor mode to keep history of played tracks
- integrated with EMMS modeline module

* Installation
** EMMS
If you haven't used it yet, then here is a minimal config.
#+begin_src emacs-lisp
(use-package emms
  :config
  (emms-all)
  (emms-default-players)
  (emms-history-load))
#+end_src
** emms-player-spotify
#+begin_src emacs-lisp
(use-package emms-player-spotify
  :straight (emms-player-spotify :type git :host github :repo "sarg/emms-spotify")

  :custom
  (emms-player-spotify-launch-cmd "flatpak run com.spotify.Client")
  (emms-player-spotify-adblock t)

  :config
  (add-to-list 'emms-player-list emms-player-spotify))
#+end_src

Install [[https://flathub.org/apps/details/com.spotify.Client][Spotify]] from FlatHub. In the app settings disable Autoplay.

* Usage
** Playing individual tracks
Tracks can be added one by one using =M-x emms-add-url= followed by a
=open.spotify.com= link. Here are example track links you can use for a test.

#+caption: TOOL-Lateralus.m3u
#+begin_example
https://open.spotify.com/track/6ZsZxNP4Iwdyp3kd5oFFQN
https://open.spotify.com/track/5aVJ5rv7ghWSkQaqP726tE
https://open.spotify.com/track/0Klbxk3g96Qae4DbCnUNcT
https://open.spotify.com/track/4KVTRIZIj1WWIxitbREDnK
https://open.spotify.com/track/55mJleti2WfWEFNFcBduhc
https://open.spotify.com/track/3EeoMkZF8NhX9FdCSxG8MB
https://open.spotify.com/track/1vxu8vMNshg5J8z3oA7QJZ
https://open.spotify.com/track/0Cnx6PGogxIE2RnDcnoeK8
https://open.spotify.com/track/7tvuLLroI0n6uYBWuFig5d
https://open.spotify.com/track/1FRlNrHd4OGNIEVgFuX9Fu
https://open.spotify.com/track/0R7HFX1LW3E0ZR5BnAJLHz
https://open.spotify.com/track/2D9rd6TIpqmDkog5Mx8kxl
https://open.spotify.com/track/3oEgMtjTzGgXTFdO0IW2M7
#+end_example

You can also save these links to a =.m3u= file and open it using =M-x emms-add-m3u-playlist=.

** Following mode
This mode is much easier to use, just add any Spotify "collection" URL, e.g. an
album or a playlist, and this collection will be expanded to individual tracks
as you listen to them. You won't be able to see the next tracks though, only the
past ones.

Try it with =M-x emms-add-url RET <link>=. E.g. [[https://open.spotify.com/album/5l5m1hnH4punS1GQXgEi3T][TOOL - Lateralus]].

Once the queue ends, the resulting playlist could be saved locally with ~C-x C-s~.
* counsel-spotify integration

[[https://melpa.org/#/counsel-spotify][counsel-spotify]] provides dynamic search functions for spotify content. Use
[[file:contrib/emms-player-spotify-counsel.el]] to integrate both. This module replaces
=counsel-spotify-do-play= with an implementation that enqueues tracks in the
current EMMS playlist. Additionally it expands albums to individual tracks.

* Timelines
#+begin_example
p - paused
> - playing
□ - stopped
m - mute
u - unmute
a - ad
[ - add temporary ad track
] - remove temporary track
+ - add track in following mode
#+end_example

** EMMS controls
#+begin_example
EMMS  >     p     >    □
------+-+---+-+---+-+--+-+--->
SPOT    >     p     >    p
#+end_example

** Spotify controls
#+begin_example
EMMS  >      p    >
------+-+--+-+--+-+--->
SPOT    >  p    >
#+end_example

** Ads in track-by-track mode
#+begin_example
EMMS  >     [m   m   u]□ >
------+-+-+-+--+-+-+-+---+-+->
SPOT    > a    a   p       >
#+end_example

** Following mode
#+begin_example
EMMS  >   +>   +>
------+-+-+--+-+--->
SPOT    >    >
#+end_example

** Ads while following
#+begin_example
EMMS  >     [m   m   u]+>
------+-+-+-+--+-+-+-+------>
SPOT    > a    a   >
#+end_example
* TODOs [2/6]
- [X] expand =spotify:album:= to a playlist
- [ ] expand =spotify:playlist:=
- [ ] better support for playlists
- [ ] implement emms-info-function to retrieve dynamic playlist names
- [ ] try "seeded" playlists  [[https://developer.spotify.com/documentation/web-api/reference/#/operations/get-recommendations][Recommendations API]]
- [X] implement seek
- drag-n-drop to emms
- playback to chromecast
